site_name: M RATHINAVELKUMAR

nav:
    - Profile Summary: index.md
    - Technical Skills: technical_summary.md
    - Project Details: project_summary.md
    - Career Summary: career_summary.md
    - Contact Details: contact_summary.md

theme:
  name: material  